version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mokasindo-app:latest
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8088}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3307}
    volumes:
      - app-data:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:1.25-alpine
    depends_on:
      - app
    ports:
      - "8088:80"
    volumes:
      - app-data:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-mokasindo}
      MYSQL_USER: ${DB_USERNAME:-mokasindo}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - db-data:/var/lib/mysql


volumes:
  db-data:
  app-data:
